import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

export default function PrivacyPage() {
  const sections = [
    { num: '1', title: 'What data we collect', content: `We collect two types of data:\n\n**Account data** (provided by you): Parent name, email address, and password. Child name, date of birth, and age. Optional: phone number and country.\n\n**Assessment data** (generated by use): Your child's answers to assessment questions. Computed scores and report content. Timestamps of assessments. Device and browser information for security purposes (IP address, browser type).` },
    { num: '2', title: 'How we use your data', content: `Your data is used solely to:\n\n• Generate personalised assessment reports for your family\n• Track your child's emotional development over time\n• Send you report-ready notifications and, if opted in, a monthly newsletter\n• Improve the quality and accuracy of our assessments (using anonymised, aggregated data only)\n• Comply with legal obligations\n\nWe do not use your data for advertising, profiling, or sale to third parties — ever.` },
    { num: '3', title: "Children's data", content: `ImoTracker is designed with children's safety as the highest priority.\n\n• **Parent-controlled access:** Only the parent account holder can create child profiles and view full reports.\n• **Minimisation:** We collect only what is necessary for the assessment to function.\n• **No direct marketing:** We never market to children or use their data for advertising purposes.\n• **COPPA compliance:** For users in the United States, we follow all requirements of the Children's Online Privacy Protection Act. See our separate COPPA Notice for details.\n• **Child-facing data:** The simplified report view children can see contains no raw scores, no clinical language, and no personal data beyond their first name.` },
    { num: '4', title: 'Data sharing and disclosure', content: `We do not sell your data. We do not share it with advertisers or data brokers.\n\nWe may share data with:\n• **Infrastructure providers** (e.g., database hosting, email delivery) under strict data processing agreements\n• **Law enforcement** only when legally required and after rigorous legal review\n\nAll third-party providers we work with are contractually required to maintain equivalent data protection standards.` },
    { num: '5', title: 'Security measures', content: `• All data is encrypted in transit (TLS 1.3) and at rest (AES-256)\n• Access to production data is restricted to essential personnel only\n• We conduct regular security reviews and penetration testing\n• In the event of a data breach, we will notify affected users within 72 hours as required by GDPR` },
    { num: '6', title: 'Your rights and choices', content: `You have the right to:\n• **Access** all data we hold about your account and children\n• **Correct** inaccurate information\n• **Download** your full data in machine-readable format\n• **Delete** your account and all associated data permanently\n• **Opt out** of non-essential communications at any time\n\nTo exercise any of these rights, use Account Settings → Data & Deletion, or email privacy@imotracker.com.` },
    { num: '7', title: 'Data retention', content: `We retain your account and assessment data for as long as your account is active. If you delete your account, all data is permanently deleted within 30 days. Anonymised, aggregated data (with no identifying information) may be retained for research purposes. Backups are purged on a rolling 90-day cycle.` },
    { num: '8', title: 'Contact', content: `For privacy questions, data requests, or concerns:\n\nEmail: privacy@imotracker.com\nResponse time: within 5 business days\n\nWe take every privacy inquiry seriously and respond to all requests personally.` },
  ]

  return (
    <>
      <Nav />
      <section style={{ background: 'var(--navy)', color: 'var(--cream)', padding: '72px 0', textAlign: 'center' }}>
        <div className="container" style={{ maxWidth: 640 }}>
          <div className="section-label" style={{ color: 'var(--coral)' }}>Legal</div>
          <h1 style={{ fontSize: 44, fontWeight: 800, letterSpacing: '-0.02em', margin: '12px 0 16px' }}>Privacy Policy</h1>
          <p style={{ fontSize: 15, color: 'rgba(245,243,239,0.6)' }}>Last updated: June 1, 2026</p>
        </div>
      </section>

      <section style={{ padding: '64px 0 96px' }}>
        <div className="container" style={{ maxWidth: 760 }}>
          {/* Plain language summary */}
          <div style={{ background: 'rgba(44,95,93,0.08)', border: '1px solid rgba(44,95,93,0.2)', borderRadius: 14, padding: 28, marginBottom: 48 }}>
            <h3 style={{ fontSize: 16, fontWeight: 700, color: 'var(--teal)', marginBottom: 12 }}>Plain language summary</h3>
            <p style={{ fontSize: 14.5, color: 'var(--navy-ink)', lineHeight: 1.65 }}>
              We collect only what we need to run the platform. We never sell your data. Your child's assessment answers are private and visible only to your family account. You can delete everything at any time. That's the short version.
            </p>
          </div>

          {sections.map(s => (
            <div key={s.num} style={{ marginBottom: 40 }}>
              <h2 style={{ fontSize: 20, fontWeight: 700, color: 'var(--navy)', marginBottom: 16 }}>
                {s.num}. {s.title}
              </h2>
              <div style={{ fontSize: 14.5, color: 'var(--navy-ink)', opacity: 0.8, lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>
                {s.content.split('\n').map((line, i) => {
                  if (line.startsWith('**') && line.endsWith('**')) {
                    return <p key={i} style={{ fontWeight: 700, margin: '10px 0 4px' }}>{line.slice(2, -2)}</p>
                  }
                  if (line.startsWith('• ')) {
                    return <p key={i} style={{ paddingLeft: 16, margin: '4px 0' }}>{line}</p>
                  }
                  if (line === '') return <br key={i} />
                  return <p key={i} style={{ margin: '6px 0' }} dangerouslySetInnerHTML={{ __html: line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
                })}
              </div>
              <div style={{ borderBottom: '1px solid var(--line)', marginTop: 32 }} />
            </div>
          ))}
        </div>
      </section>
      <Footer />
    </>
  )
}
